apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  annotations:
        autoscaling.knative.dev/min-scale: "2"
        autoscaling.knative.dev/maxScale: 3
  name: tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-web-app
spec:
  source:
    git:
      url: https://github.com/ydaoqi/tanzu-java-web-app
      ref:
        branch: main
